### ISSUE TITLE
TypeError: response.enhance is not a function

### ISSUE THREAD

**Issue by kjjgibson** [tulios/mappersmith#104]
If an error is thrown when doing a request and you're using the RetryMiddleware then the initial error will be swallowed and Mappersmith will throw an error instead. This makes it impossible to debug the actual problem.

```
Exception has occurred: TypeError
TypeError: response.enhance is not a function
    at enhancedResponse (/Users/kenneth.gibson/klarna/klarna-app/services/orders/node_modules/mappersmith/middleware/retry/v2/index.js:117:19)
    at /Users/kenneth.gibson/klarna/klarna-app/services/orders/node_modules/mappersmith/middleware/retry/v2/index.js:87:88
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by tulios** [comment]
I think some middleware is changing the response because the retry middleware is prepared to handle failures. In this case, it is receiving something different. Maybe I could log the response if it isn't a Response object. WDYT?

**Comment by kjjgibson** [comment]
Solved with the following: https://github.com/tulios/mappersmith/pull/118
