### ISSUE TITLE
RetryMiddleware shared examples tests not running.

### ISSUE THREAD

**Issue by jbeuckm** [tulios/mappersmith#108]
Something async or with how Jest wants the structure is causing tests in  `/spec/browser/middleware/retry/shared-examples.js` not to run.

**Comment by tulios** [comment]
I think you can't run the tests directly with jest; you have to use the yarn commands.

yarn 

`test:browser`
`test:browser:integration`
`test:browser:watch`
`test:node`
`test:node:integration`
`test:node:watch`

-- this command runs all the tests (integration + unit)
`test`

**Comment by jbeuckm** [comment]
I am passing `yarn test:node && yarn test:browser` locally and I think the pipeline passes with this line:

https://github.com/jbeuckm/mappersmith/commit/9e22ac350b5c51aebe5c991a196e331776359cf1#diff-31c89a1400440944e8819670912e0907R23

**Comment by jbeuckm** [comment]
Updating jest per Tulios recommendation... https://github.com/jbeuckm/mappersmith/tree/bump-jest-version
