### ISSUE TITLE
Identifying 502 bad gateway errors

### ISSUE THREAD

**Issue by fgameiro** [tulios/mappersmith#123]
When trying to understand some API calls returning a `502 bad gateway` error, I found out that mappersmith returns, in this case, a default status code of `400` and the `Network error` message. So I am unable to filter out these failed calls through the lib.

Is this an expected result or is it a bug? Is there a way to get a response object with the status code `502`?

**Comment by tulios** [comment]
@fgameiro sorry for the delay, mappersmith should only return 400 for network errors, but I can see a potential bug on the node http gateway, are you talking about node.js?

https://github.com/tulios/mappersmith/blob/7381e226be5f7dde4fb1870b6e9f0113608305ef/src/gateway/http.js#L108-L113

This might be happening for 502, I can double check

**Comment by fgameiro** [comment]
hey @tulios, thanks for the response!

No, actually the problem is happening on browser, but after further checking, we found out that what is probably happening is that the cloudflare service we use is masking our server's 502. Then, we can't reach the cloudflare's 502 because of their lack of `Access-Control-Allow-Credentials`.

After all this, we conclude that mappersmith is getting an errored response as we expect, but without any info, so we get some sort of default response (the 400 status code and the `Network error` message).
