### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by deowk** [tulios/mappersmith#14]
Hi Guys,

Just wondering if you could shed some light in terms of browser support? Would this library be safe to use in IE8?

Thanks...

**Comment by tulios** [comment]
Hi @deowk, when we design mappersmith we have considered just modern browsers but currently we don't use anything fancy thus the methods which IE8 doesn't have can easily me included by a shim. We use `bind`, `map`, `reduce`, `filter`, `forEach` and `Object.keys`. Something like [es5-shim](https://github.com/es-shims/es5-shim) or even a snippet like [ie-shims](https://gist.github.com/dhm116/1790197) can do the job.

**Comment by deowk** [comment]
Thanks for the quick reply...;)

How about handling CORS from the client side, there are a couple of nuances with older browsers especially IE8 & 9....?

**Comment by tulios** [comment]
Yeah, we can definitely do that. I am working on a `FetchGateway` using the new `fetch` api, I think it will be easier to use this gateway but we also have to improve the vanilla gateway. I will leave this issue open and create another to handle the CORS support.

**Comment by deowk** [comment]
Sounds good to me, maybe improve the docs to specify browser support - usually one of the first things people look at when thinking of using a library in production....;)

**Comment by tulios** [comment]
I included a section about the browser support
