### ISSUE TITLE
Supply a function for 'path' of a method.

### ISSUE THREAD

**Issue by jbeuckm** [tulios/mappersmith#159]
Use a function on passed params to rewrite the path.

*Use case:*
I have 10,000 files organized into subsequent character folders like `/data/1/2/3/4.json`. To get the data, I should use `Resource.byId({id:1234})` to perform a GET request at `/data/1/2/3/4.json`. 

```
const api = forge({
  host: 'https://data.com',
  resources: {
    Resource: {
      byId: { path: ({id})=>`/data/${id.split(''}.join('/')}.json` },
    }
  }
})
```

**Comment by tulios** [comment]
#186 was merged
