### ISSUE TITLE
Define query parameters when forging new clients

### ISSUE THREAD

**Issue by mnmtanish** [tulios/mappersmith#188]
Hi @tulios 
Thanks for the awesome package. Are you interested in defining query parameters when creating clients. If we know which query params are available, we can validate whether the client is trying to send invalid params or if it's missing mandatory query params.

We can also define whether the query param is required or not. It may not make sense in some cases but I have seen many APIs with mandatory query params.

```ts
forge({
  resources: {
    Hello: {
      // if the value inside query object is `true` it is required, if it's `false` it's optional
      // if the query is defined, throw errors/warning if other query params are used
      get: { method: 'get', path: '/hello', query: { firstName: true, lastName: false } },
    },
  },
})
```

**Comment by tulios** [comment]
Hi @mnmtanish, what about validating the request with a middleware? Let's say, something like:

```js
forge({
  resources: {
    Hello: {
      get: {
        method: 'get',
        path: '/hello',
        middleware: [ValidateQueryParams({ required: ['firstName'] })]
    },
  },
})
```

**Comment by mnmtanish** [comment]
Cool, I'll give it a try
