### ISSUE TITLE
Response.data() silently failing when parsing invalid JSON

### ISSUE THREAD

**Issue by PhilipNilssonKlarna** [tulios/mappersmith#197]
When getting a response back from an API and calling the ´.data()´ function on the response object, it will swallow any error from trying to parse the JSON. If it fails it will just return the string data. What is the reasoning behind this decision? as it seems odd to not just throw an error here as if you're expecting an object back and get something invalid then it should throw an error.

The function in question: https://github.com/tulios/mappersmith/blob/master/src/response.js#L92

**Comment by klippx** [comment]
At the surface, There are 4 basic cases to consider here:
1. Invalid JSON in `rawData` and headers are NOT content-type json => returns `rawData` - This is OK!
2. Valid JSON in `rawData` and headers are NOT content-type json => still returns `rawData` - This is OK!
3. Valid JSON in `rawData` and headers are content-type json => returns `JSON.parse(rawData)` - This is OK!
4. Invalid JSON in `rawData` and headers are content-type json => returns `rawData` - "This seems odd, it should throw" <-- this is the case we want to discuss

So before answering why (4) behaves like this, let's think about why would a case like (4) even happen? Here is my I guess:
**Reason A:** A content-type json header was incorrect set by the remote while sending a plain text body. 
**Analysis A:** In this case you as the caller didn't expect JSON back anyway, you expected text so it is actually _GOOD_ that it doesn't throw in this case.

**Reason B:** A content-type json header was correctly set by the remote, but it has problems serializing json and also didn't validate it. 
**Analysis B:** In this case you are expecting JSON, I agree that in this case you would expect mappersmith to throw actually. 

But in the end, I don't think A is about a million times more likely to happen than B, so I would not agree to change the code with my current understanding. But maybe I am missing something?

If this really is a problem, I can offer a workaround that you can use `rawData()` instead and do your own JSON parsing just to be sure.
