### ISSUE TITLE
Headers are not available on the response object when the request fails

### ISSUE THREAD

**Issue by marano** [tulios/mappersmith#199]
Not sure if this is a bug. I would like to access the headers on the response object when a request fails.
```js
client.Resource
  .get(...)
  .catch(response => {
    response.headers() // not a method error
  })
```

**Comment by tulios** [comment]
Are sure that you are receiving mappersmith's response object? There are event tests for that https://github.com/tulios/mappersmith/blob/4347b26869980205a9cd2e3c917784044efc632a/spec/browser/gateway/xhr.spec.js#L90-L92
