### ISSUE TITLE
Improve defaults to avoid SSRF

### ISSUE THREAD

**Issue by ctaintor** [tulios/mappersmith#204]
Currently mappersmith can make it easy for someone to write code that is susceptible to [SSRF](https://en.wikipedia.org/wiki/Server-side_request_forgery). This is because any individual request can have the `host` attribute overridden _and_ the `host` can be a full path. A few ways this could be solved:

• make it easier to disable/remove this feature
• only allow `host` to be a host (and not a full path)

Other ideas?

**Comment by eggli** [comment]
Would be nice to have a `strictHost` parameter to control this while forging it.

**Comment by tulios** [comment]
Hey @ctaintor, this makes a lot of sense and I think both options apply. I intend to work on this ASAP as I consider having at least an option to disable the host override critical.

Thanks

**Comment by tulios** [comment]
PR #205 changes mappersmith to require a configuration `allowResourceHostOverride: true` in order to use host overrides, the default value is false.

**Comment by tulios** [comment]
Version `2.34.0` is out and has the new parameter disabled by default.
