### ISSUE TITLE
Include a way to assign headers direct from the call

### ISSUE THREAD

**Issue by tulios** [tulios/mappersmith#21]
In the issue #20 @CezarLuiz0 asked about a better way to assign headers and I think this is reasonable.

The proposal is:

```javascript
Client.Photo.save({
  params: { category: 'family' },
  body: {year: 2015, tags: ['party', 'family']},
  headers: {
    'Authorization': 'token MYTOKEN'
  }
})
```

**Comment by CezarLuiz0** [comment]
The way axios work looks interesting.

https://github.com/mzabriskie/axios
