### ISSUE TITLE
Export Named Function 'Response'

### ISSUE THREAD

**Issue by elmpp** [tulios/mappersmith#224]
I'm building a cache middleware that will dip into Redis and conditionally return cached values as a Response.

However, it seems that the named function 'Response' is not exported (v2.34.0) from the package. I understand that [enhance](https://github.com/tulios/mappersmith#-middleware) is the proscribed method of creating responses but this requires first resolving the 'next' `ResponseGetter`. 

As I want to avoid making the request at all when cached, I would like to create the Response explicitly.

This is the workaround solution atm:

```
/typings/mappersmith.d.ts

interface ConstructableResponse {
  new (
    originalRequest: any,
    responseStatus: any,
    responseData: any,
    responseHeaders?: any,
    errors?: any
  ): import('mappersmith').Response
}
declare let response: ConstructableResponse

declare module 'mappersmith/response' {
  export default response
}
```

```
import { Request, RequestGetter, Middleware, ResponseGetter } from 'mappersmith'
import ResponseInit from 'mappersmith/response'  // <---  

type CachedResponse = {
  status: ReturnType<Response['status']>
  data: ReturnType<Response['data']>
  headers: ReturnType<Response['headers']>
}

export const createRedisCacheMiddleware = (
  redis: Redis,
  cacheDuration: number,
  logger: KlarnaLogger
): Middleware => () => {
  let requestHandle: Request
  return {
    async prepareRequest(next: RequestGetter): Promise<Request | void> {
      const request = await next()
      requestHandle = request
      return requestHandle
    },

    async response(next: ResponseGetter): Promise<Response | Record<string, any>> {
      if (requestHandle.method() !== 'get') {
        return next()
      }

      const url = requestHandle.url()
      const cacheKey = `url:${url}`
      const cachedEntry = await redis.get(cacheKey)
      if (cachedEntry) {
        logger.debug(`RedisCacheMiddleware: HIT for key '${cacheKey}'`)

        const { status, data, headers } = JSON.parse(cachedEntry) as CachedResponse
        const regeneratedResponse = new ResponseInit(requestHandle, status, data, headers)
        return regeneratedResponse
      }

      const cacheableResponse = await next()
      logger.debug(`RedisCacheMiddleware: MISS for key '${cacheKey}'`)
      await redis.set(
        cacheKey,
        JSON.stringify({
          status: cacheableResponse.status(),
          data: cacheableResponse.data(),
          headers: cacheableResponse.headers(),
        }),
        'EX',
        cacheDuration
      )

      return cacheableResponse
    },
  }
}
```

**Comment by tulios** [comment]
Hi @elmpp, your need makes sense, but what can't you do by importing `mappersmith/response`? I think am a bit confused about what you need. However, you should be able to accomplish what you want with the current version.

**Comment by elmpp** [comment]
Hi @tulios 

I can certainly get by with the current solution. There's certainly no urgency in any case :) 

However, I think this use case shows there's a valid need for accessing `Response()`. As a result, I'd expect it to be a top level package export (named export from `mappersmith`) and thus be included in the API docs and type declarations.

**Comment by tulios** [comment]
It makes sense @elmpp. I will keep this issue opened until I can make the change. It should be simple do change.

**Comment by klippx** [comment]
Fixed in #264

**Comment by fustarstefan** [comment]
Hi, is there a chance that you could help me with figuring out how would this example look like now with the fix.

**Comment by klippx** [comment]
`import { Response } from 'mappersmith'` gives you access to the class constructor. I have also made this type of middleware myself so I have some experience.

I did like this, roughly:
```
import { Response } from 'mappersmith';

export const RequestCache = (): Middleware => {
  ...
  async response(next, _, request) {
    ...
    if (cachedSerializedData) {
      const data = deserialize(cachedSerializedData)
      return new CachedResponse(data, request);
    }
```

Where `CachedResponse` is a wrapper for Response.
```
export class CachedResponse extends Response {
  constructor(
    public _data: unknown,
    public _request: Request,
    public _status = 200
  ) {
    super(_request, _status, _data as any);
  }
}
```

This way my other code can tell if this was a cached response or not, which can help reduce confusion in logs or while debugging as cached responses is a source of mental indirection.
