### ISSUE TITLE
Retry middleware should let you configure HTTP verbs

### ISSUE THREAD

**Issue by edvinerikson** [tulios/mappersmith#244]
## Why

I have a scenario where I would want to retry a POST request and since we are already using the retry middleware for GET requests, I think it would make sense to re-use it for POST requests too. 

## What

Add a `httpVerbs` list to the config and switch the `enableRetry` to check that list. It should default to GET in order to be backward compatible.

**Comment by Nevon** [comment]
See #218 and #234 for previous discussions on this.

**Comment by klippx** [comment]
The solution Edvin went for in the end was to create a local retry middleware function generator that checks for presence of a configurable headerIdempotencyId  in headers, but which can be configured to allow retrying non-idempotent requests without such header by passing in an option `dangerouslySkipIdempotencyCheck` which defaults to `false`.
