### ISSUE TITLE
feature request: mockRequest should support "mock once" behaviour 

### ISSUE THREAD

**Issue by edvinerikson** [tulios/mappersmith#246]
# Suggestion
When a mock has been used it should be removed/ignored. This would allow for a behaviour where an endpoint can return different results during different requests. 

# Background
I was trying to simulate request retries where an endpoint would first fail (500 status code), then succeed (200 status code) during a retry. However I did not manage to simulate this with the mappersmith/test module. 

```js
const errorMock = mockRequest({
  method: 'get',
  url: `/hello`,
  response: {
    status: 500,
  }
})

const successMock = mockRequest({
  method: 'get',
  url: `/hello`,
  response: {
    status: 200,
  }
})

await executeRequest() // <-- call mappersmith client with retry middleware
expect(errorMock.callsCount()).toEqual(1)
expect(successMock.callsCount()).toEqual(1)
```

**Comment by Nevon** [comment]
The mockClient `response`, `status` and `headers` can all be provided functions where you can implement this. See this for an example:

https://github.com/tulios/mappersmith/blob/2093d4a759618f9d4c704e03964d0a9b9a46abd2/spec/browser/test/mock-resource.spec.js#L168-L175

**Comment by edvinerikson** [comment]
We usually follow a pattern where we don't export the mappersmith client. Is it possible use mockClient without passing a client reference?

**Comment by klippx** [comment]
Take a look at this example:
https://github.com/tulios/mappersmith/blob/0067c23c859043cde345bdf166c8382af1255393/spec/browser/test/mock-request.spec.js#L338-L347

Check how this spec forges a client, `install()` and `uninstall()`.

What we don't know given your pseudo code is what `executeRequest()` does. But if you compare notes with the example above it seems that it should work, try `unusedMocks()` and/or adding some debug logs in your implementation.

**Comment by klippx** [comment]
It works in `mockRequest` as well:
```js
      mockRequest({ method: 'get',
        url: 'http://example.org/users?sort=desc',
        response: {
          handler: (request, mock) => mock.callsCount() === 0 ? 'first' : 'second',
          status: (request, mock) => mock.callsCount() === 0 ? 500 : 200
        }
      })

      await client.User.all({ sort: 'desc' }).catch((e) => console.error(e.status()))
      await client.User.all({ sort: 'desc' }).then((r) => console.log(r.status()))
```

Result:
```
  console.error 
    500

  console.log 
    200
```
