### ISSUE TITLE
wrong content-type on vanilla gateway

### ISSUE THREAD

**Issue by gbrlsepulveda** [tulios/mappersmith#25]
Hi, i was trying to send a request with `Content-Type: application/json` and i got a response status 500, looking the `Content-Type` on network request I noticed that all headers doesn't concatenating correctly.

Example: `application/x-www-form-urlencoded; charset=UTF-8 application/json`
Should be: `application/x-www-form-urlencoded; charset=UTF-8; application/json`

I prepared a pull request to solve

**Comment by tulios** [comment]
I've published version 0.13.1 with your fix. Thanks again!
