### ISSUE TITLE
Typing client responses

### ISSUE THREAD

**Issue by klippx** [tulios/mappersmith#263]
## No typing of client responses

By default a forged resources returns a promise of `any`:
<img width="632" alt="Screenshot 2021-12-13 at 08 38 12" src="https://user-images.githubusercontent.com/2785359/145771192-d634ba47-56d9-43df-a1dc-e2d2cc4718bc.png">

To improve this, you have a few options listed below.

### Type response with a custom interface
<img width="557" alt="Screenshot 2021-12-13 at 08 40 22" src="https://user-images.githubusercontent.com/2785359/145771496-374d23c8-db77-4352-ae29-ea92caa829e7.png">

The advantage here is that we defined the type of all client invocations in one single place.
The disadvantage is that we replaced the `response` type of a clean `Response` with a dummy type: `{ data: () => ... }`

### Type response while accessing it
You can alternatively at the point of invoking client use generic typing on `.data<T>()`:
<img width="546" alt="Screenshot 2021-12-13 at 08 41 43" src="https://user-images.githubusercontent.com/2785359/145771968-ee446dd9-ac6c-4f89-bcd5-3b6fd51f6e0e.png">

The advantage here is keeping `response` as `Response`.
The disadvantage is that it needs manual typing everywhere we use it.

## Proposal
The best of both worlds could look something like this:
<img width="554" alt="Screenshot 2021-12-13 at 09 19 13" src="https://user-images.githubusercontent.com/2785359/145776399-42a03fac-5acf-4119-8c59-d9eb3078683b.png">

The advantage here is keeping `response` as `Response`.
The advantage here is that we defined the type of all client invocations in one single place.
No disadvantage. You can still manually override the response type on `.data<T>()` if necessary.

**Comment by jbeuckm** [comment]
Is there a more succinct way to communicate the response shape than the manual specification above? It would be great to also specify (or derive) the request shape like `User.all: Method<RequestType, ResponseType>` rather than repeating `(x:RequestType) => Promise<Response<...` which I believe is the form for every method.

**Comment by klippx** [comment]
@jbeuckm I suppose it could, not sure how though. I guess the approach could be to investigate if the argument to forge `options: ManifestOptions<Resources>` could be pried open to accept a richer type for `Resources extends ResourceTypeConstraint` which matches the given objects and has the type information needed.

I would suggest creating a new issue and investigating it there ❤️

**Comment by klippx** [comment]
Fixed in #264
