### ISSUE TITLE
Hook beforeSend

### ISSUE THREAD

**Issue by ericholiveira** [tulios/mappersmith#28]
It would be good to have a hook like the beforeSend on Jquery ajax. Sometimes you might want to change some headers dinamically  (im passing user auth token on header and this token can change as the user login/logoff my application). This way i could check storage/memory before sending the request for the current token.

**Comment by tulios** [comment]
I had this necessity myself in the past (issue #15) and, in the end, I solved the problem in a different way. This feature combined with URL matching and global configurations can be really powerful. I'll keep this issue open to track the addition of this feature.

Thanks again.

**Comment by ericholiveira** [comment]
This is not a block to me a just made a proxy function to the .forge result. But is certainly a nice-to-have feature to make it more powerful
