### ISSUE TITLE
Empty string responses are transformed to null

### ISSUE THREAD

**Issue by katrotz** [tulios/mappersmith#297]
When the remote returns an empty string response ``, mappersmith transforms the response to `null`.

This happens because the duration middleware uses response enhance (see [here](https://github.com/tulios/mappersmith/blob/master/src/middleware/duration.js#L22)), which defaults to `undefined` for "falsy" responses (see [here](https://github.com/tulios/mappersmith/blob/master/src/response.ts#L156)), which is mapped to `null` (see [here](https://github.com/tulios/mappersmith/blob/master/src/response.ts#L48))

### Steps to reproduce
1. Return an empty string as response from remote

### Expected
Mappersmith returns the original empty string response

### Actual
Mappersmith maps the empty string to `null`

**Comment by klippx** [comment]
The fix has now been relased in `2.38.1`
