### ISSUE TITLE
MockRequest does not work for response data of type Buffer

### ISSUE THREAD

**Issue by katrotz** [tulios/mappersmith#299]
The change introduced in this [PR#294](https://github.com/tulios/mappersmith/pull/294/files#diff-ba6b8671b10212d39ddbd5d843e770ef2f90c53d059ca5f8f7c1d8384c718648L3) that clones the fixtures breaks the tests where the mocks are Buffers.
Same happens when the response is a typed array (eg. Uint8Array)

**Expected**:
When the mockRequest body is not a plain object, do not clone it, or clone it using specialised methods (eg. for Buffers Buffer.from, for Uint8Array Uint8Array.from, etc.)

**Actual**:
The buffer mock response is cloned into a plain object

**Comment by klippx** [comment]
Related: #286

**Comment by klippx** [comment]
The fix has now been relased in `2.38.1`
