### ISSUE TITLE
Needs additional error handling for onSuccess callback

### ISSUE THREAD

**Issue by drywolf** [tulios/mappersmith#30]
Hi,

I came across the case that I have an error that is thrown in the code that is executed in the "onSuccess" callback of a mappersmith request.

![image](https://cloud.githubusercontent.com/assets/394294/15245471/f8696144-1906-11e6-89ab-47a3ec7efd16.png)

In the [vanilla-gateway.js#L85](https://github.com/tulios/mappersmith/blob/master/src/gateway/vanilla-gateway.js#L85) this error is caught and treated as if it was a mappersmith error. That leads to a very confusing error that is shown in the developer-tools because it looks just like a API request error...

![image](https://cloud.githubusercontent.com/assets/394294/15245518/50e4b9c2-1907-11e6-85f9-182d763feee5.png)

There are no hints about the original error that was happening in the onSuccess callback.

I would propose that there is an additional catching of errors that happen in the onSuccess callback like so:

```
    try {
      this.successCallback(data, extra);
    }
    catch(e) {
      this.failCallback({status: status, args: [e]});
    }
```

... at [vanilla-gateway.js#L80](https://github.com/tulios/mappersmith/blob/master/src/gateway/vanilla-gateway.js#L80)

This way, the original error is passed as the second parameter to the failCallback and can be gracefully handled.

PS: I think the other gateway implementations might be prone to the same behavior, I only debugged the vanilla-gateway though.

Regards

**Comment by tulios** [comment]
Hi, really good description. Thanks. I think it makes sense, I'll see if I can start doing this soon! Thanks again.

**Comment by tulios** [comment]
Version 2.0.0 is handling this in a better way now. I'll close this ticket for now but feel free to reopen or create a new one if this is not improved for you.

Thanks
