### ISSUE TITLE
Not possible to post with body using VanillaGateWay

### ISSUE THREAD

**Issue by klippx** [tulios/mappersmith#31]
Reproduce:

https://github.com/klippx/roger/tree/mappersmith-issue

This commit breaks the express middleware: https://github.com/klippx/roger/commit/79d54e3fc9757d3209d29f8f0708bc75338edf1e

If I start the app and post the form using commit https://github.com/klippx/roger/commit/9acdf0acbdfacd8d9852e2b6aab53abb2b6aa256 I get this output in backend:
```console
App running at http://localhost:3100/
GET /links.json {}
fetching {links} from graphql
--bodyParser: URLENCODED--, encoding: utf-8
POST /links/create.json { title: '123', url: 'abc' }

 == create-link handler ==
body: { title: '123', url: 'avc' }
```

But without jquery/jquery gateway I get this:
```console
App running at http://localhost:3100/
GET /links.json {}
fetching {links} from graphql
POST /links/create.json {}

 == create-link handler ==
body: {}
creating new {link} in graphql
    mutation {
      add(title: undefined, url: undefined) {
        id, title, url
      }
    }
```

As you can see above, it totally skipped the express bodyParser middleware.

Curl is always possible regardless of commit sha:

```console
curl -H "Content-Type: application/json" -X POST -d '{"title":"xyz","url":"http://123"}' http://localhost:3100/data/links/create.json
```

**Comment by tulios** [comment]
Thanks! As stated [here](https://www.w3.org/TR/html5/forms.html#url-encoded-form-data) `application/x-www-form-urlencoded` doesn't have charset defined in the header,  I was able to replicate the problem with curl:

```sh
curl -v \
  -XPOST \
  -H 'Content-Type: application/x-ww-form-urlencoded; chartset=utf-8;' \
  -d "title=test1&url=test2" \
  http://localhost:3100/data/links/create.json
```

Removing __charset=utf-8__ fixes the problem. A bugfix version is on its way!
