### ISSUE TITLE
Mappersmith doesn't support service workers

### ISSUE THREAD

**Issue by BooleT37** [tulios/mappersmith#311]
Hi! I'm from the team that develops a browser extension. We're currently migrating to [manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/), and we have encountered an issue with Mappersmith.

Manifest v3 uses service workers. And when we initialize the Mappersmith, it throws this error:
```
[Mappersmith] gateway class not configured (configs.gateway)
```
([src/client-builder.ts#L58](https://github.com/tulios/mappersmith/blob/6d5386351af7575f8e83883021d7e64964c501ef/src/client-builder.ts#L58))

The reason for it is that we do not initialise the gateway in [src/index.js](https://github.com/tulios/mappersmith/blob/6d5386351af7575f8e83883021d7e64964c501ef/src/index.js#L11) for service workers, we only do it for node and browser environments.

**Comment by klippx** [comment]
Fixed by #310
