### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by ItaloSampaio** [tulios/mappersmith#33]
Hi, guys! First of all, awesome work!

I'm trying to figure out how to upload a file using FormData and mappersmith. Any example or idea will be appreciated.

Thanks!

**Comment by ItaloSampaio** [comment]
Hi again!

Digging into source code, I discovered that my FormData was not being processed, because it was handled like a ordinary object in Utils.params function. I solved it putting a checking for a FormaData instance:

utils.js
...
`function isClientSide() {  return typeof window !== 'undefined' && window !== null; 
}`
...
`params: function(entry) {
  if (typeof entry !== 'object' || (isClientSide() && entry instanceof FormData)) {
      return entry;    
}`
...

I had to put the client side checking because of server side compatibility. That done, I discovered other problem. See my POST request:

...
`API.Audios.create(
                {
                    body: formData,
                    headers: { "cache-control": "no-cache"}
                },
                {
                    contentType: false,
                    processData: false,
                    mimeType: "multipart/form-data"
                }
             ).then(response => 
                dispatch(createSuccess(response.data))
            )`
...

I'm passing jQuery options in second parameter and, because of that, the callback inside of newGatewayRequest() in mapper.js receives a noop function. And, how can you see in the code above, I'm using promises. So this two things makes the returned response "undefined". I fixed it assigning to the callback an undefined value when using promises.

mapper.js
...
`newGatewayRequest: function(descriptor) {
...
      else if (callback && typeof callback !== 'function') {
        opts = callback;
        callback = !Env.USE_PROMISES
          ? Utils.noop
          : undefined;
      }`
...

This prevent the gateway to promisify the noop function. Running the tests, everything looks fine, but tell me what do you think.

**Comment by tulios** [comment]
Hi @ItaloSampaio, sorry for the delay, I'm in the middle of a hackaton this weekend but I give this some time during the week.

1) It should work with `FormData`, so your first point is the way to go, we should fix mappersmith (I have a different implementation in mind but the overall ideia is the same)

2) Instead of changing the mapper we should change `JQueryGateway` to ensure the callbacks

Mappersmith 2 is on its way with a better internal structure, and thanks to your issue I'll pay more attention to this use case :)

**Comment by joelwallis** [comment]
@ItaloSampaio just show me that issue and project, and hell what a project! 😃

Hey Italo, I think we could even work on this issue together, and make our first contribution to Mappersmith, what you think? @tulios could help us with advises regarding architectural concerns and we could work on the implementation (assuming that Mappersmith currently does not support multidata powered POSTs - or those needed to transfer files through HTTP).

I subscribed to this issue, and I would be glad to contribute :-)

**Comment by joelwallis** [comment]
Just curious: it look a lot like `$resource` from AngularJS (branch 1.x). Did it inspired you to build Mappersmith, @tulios?

**Comment by ItaloSampaio** [comment]
No problem, @tulios. This was freaking me out because I was thinking I'm doing something wrong. If you don't mind, you could point us the direction. I'm new in the comunity like a collaborator, so @joelwallis could help me with it.

**Comment by tulios** [comment]
Amazing guys, we can bounce ideas and you can definitely drive the coding :) 🎈 

@joelwallis I never worked with Angular and I wasn't aware of `$resource`, interesting to see the similarities.

About the changes:

1) `VanillaGateway` should support `FormData`, so I propose a change here:
https://github.com/tulios/mappersmith/blob/master/src/gateway/vanilla-gateway.js#L50

something like:

```javascript
if (this.body !== undefined) {
  args.push((this.body instanceof FormData) ? this.body : Utils.params(this.body));
}
```

quick and dirty just to show the idea. This should fix uploads with `VanillaGateway`, the final API should be:

```javascript
var formData = new FormData()
formData.append('file', file) // eg: file = $('input[type=file]')[0].files[0]

Client.MyResource.upload({
  body: formData,
  headers: { 'content-type': 'multipart/form-data' }
})
```

2) Your first comment regarding the callback function is right, I think your solution is good. If you are using promises, skip the callback with `noop`

**Comment by ItaloSampaio** [comment]
@tulios, we could centralize checking for a FormData body in Utils.params. This works for both cases, JQuery and Vanilla, how I did suggest on the first time. What do you think? Does something bother you about this approach?

**Comment by tulios** [comment]
I just think that `Utils.params` is just a helper and it should be agnostic of the details, `FormData` is related to how browser gateways handle file uploads, thus I think it should be implemented on the gateways, even if it adds some duplication. However, I don't want to force anything, we can discuss and decide together what is the best approach.

Another solution is to improve `Utils.params` to check if entry is a plain object, because the original idea of this object check was to allow users to use other stuff as body.

something like this:

```javascript
function isPlainObject(value) {
  if (!Object.prototype.toString.call(value) === '[object Object]') {
    return false
  }

  return Object.getPrototypeOf(value) ===
    Object.getPrototypeOf({})
} 

// ...

params: function(entry) {
    if (!isPlainObject(entry)) {
      return entry;
    }
    // ...
}

// ....
```

**Comment by tulios** [comment]
Hey guys (@ItaloSampaio and @joelwallis), how is it going here? Do you guys need any help?

**Comment by ItaloSampaio** [comment]
Hi, @tulios. Sorry for the hiatus. It's good solution. I found similar contents in my research for this case. I'll back to work on it this weekend, because I' finishing a project this week. @joelwallis is helping me with the process. Thanks!

**Comment by tulios** [comment]
Hey guys, version `2.0.0-rc1` is out and this operation should be really simple now. You can do something like this:

```javascript
// Imagine we already have our client

const selectedFile = document.getElementById('input').files[0]
const formData = new FormData()
formData.append('myfile', selectedFile)

Client.Pictures.upload({ body: formData })
```

**Comment by ItaloSampaio** [comment]
Great! Thanks, @tulios.
