### ISSUE TITLE
Content-Length header error

### ISSUE THREAD

**Issue by refast** [tulios/mappersmith#35]
Sorry, but you don't have to set manually "Content-Length" header in Gateway, it causes browser error.

> xhr.js:87 Refused to set unsafe header "content-length"

**Comment by tulios** [comment]
Interesting, I've never had this error. I can remove `Content-Length`, thank you!

**Comment by tulios** [comment]
@refast I've released version `2.0.0-rc2` with the fix. Thanks again!

**Comment by refast** [comment]
@tulios thank you for good library & support
