### ISSUE TITLE
2.42.0-beta.1 is published to NPM as latest

### ISSUE THREAD

**Issue by MykhailoMatiiasevych** [tulios/mappersmith#375]
Version [2.42.0-beta.1](https://www.npmjs.com/package/mappersmith/v/2.42.0-beta.1) is published to NPM as latest as so bing installed by npm by default

**Comment by klippx** [comment]
v2.42.0 is now published. We introduced changesets which automatically tagged this as v2.42.0 (note the prefix `v`) which is curious detail, that we will have going forward.
