### ISSUE TITLE
fetch compatible gateway

### ISSUE THREAD

**Issue by rwillrich** [tulios/mappersmith#54]
Hi @tulios! 

I was wandering if there are any gateway implementations using `fetch` instead of `jQuery.ajax`? If aren't any, what do I need to implement one?

**Comment by rwillrich** [comment]
Sorry, I haven't seen there was a mention of it at the Readme, I'm closing the issue... 😛

**Comment by tulios** [comment]
❤️

**Comment by tulios** [comment]
Just be aware that this is for version 2.

**Comment by rwillrich** [comment]
Yep, I'll have to update to it first. We're still in v0.12.

**Comment by tulios** [comment]
It shouldn't be too hard to upgrade, I should have written an upgrade guide :/

Anyway, it should also be simple to write a gateway for version 0.x as well, but I would recommend version 2 as it has a lot of improvements and with the middleware support it is super flexible.
