### ISSUE TITLE
Option to change bodyAttr

### ISSUE THREAD

**Issue by sximba** [tulios/mappersmith#56]
Hi @tulios 

Prior to version 2.0.0 we had something like this:
Mappersmith.forge(Manifest, Gateway, "data")

Is there a way to achieve the same (pass a custom bodyAttr) on version >= 2.0.0?

PS: If possible, can you put together a minimal migration guide?

**Comment by tulios** [comment]
Yes :)

You can take a look here (https://github.com/tulios/mappersmith#body), but in a nutshell you can use the `bodyAttr` when defining your methods, example:

```
// ...
{
  create: { method: 'post', path: '/blogs', bodyAttr: 'payload' }
}
// ...

client.Blog.create({
  payload: {
    title: 'Title',
    tags: ['party', 'launch']
  }
})
```

**Comment by sximba** [comment]
Is it not possible to make it a global config like before?

**Comment by tulios** [comment]
Currently it's not possible, is it something you would like to have?

**Comment by sximba** [comment]
Yeah. It would be nice to have some of the resource attributes i.e bodyAttr, headersAttr and authAttr configurable at a higher level than resource definition, like host.

My thinking behind this is that they are less likely to change than path and method. So that something like the following is possible:
const client = forge({
  host: 'https://status.github.com',
  bodyAttr: 'data',
  headersAttr: 'h',
  resources: {
    User: {
      all: { path: '/users' }
    }
  }
})
