### ISSUE TITLE
setContext does not unset the value when undefined is passed

### ISSUE THREAD

**Issue by TrustNik** [tulios/mappersmith#81]
Hi there! 
Thanks for an awesome lib 👍 

I have got into an issue with setContext feature in the following case:

```javascript
setContext({key: 'value'})
...
setContext({key: undefined})
```
Second call does not override the value, so it stays 'value'. That could be misleading.
Thoughts?

**Comment by tulios** [comment]
This should definitely be fixed, `setContext` should set `undefined` keys to null to force the removal.

**Comment by tulios** [comment]
@TrustNik I wrote a test trying to simulate the issue but it didn't happen in my test, any ideas?

```javascript
it('unset the value of a key', () => {
  configs.context = {}
  setContext({ foo: 'bar' })
  setContext({ foo: undefined })
  expect(configs.context).toEqual({ foo: undefined })
})
```

![screen shot 2018-01-11 at 10 30 17](https://user-images.githubusercontent.com/33231/34818214-766a1ad8-f6ba-11e7-8925-291b7d5bbf7b.png)

**Comment by TrustNik** [comment]
@tulios I double checked the issue and it turns out that the bug was in my code not in mappersmith.  Sorry for confusion, closing this one.
