### ISSUE TITLE
IE11: headers are not parsed correctly

### ISSUE THREAD

**Issue by ruspython** [tulios/mappersmith#94]
Response headers are not parsed correctly in IE11. For example Content-Type, `responseHeaders` property looks like this
```
{ '\ncontent-type': 'application/json; charset=utf-8' }
```

**Comment by tulios** [comment]
I'll take a look, thanks

**Comment by tulios** [comment]
Hi @ruspython, I wasn't able to reproduce this error, but a `trim` was missing in the key sanitization. Version `2.20.0` has the fix, can you give it a try?

I will consider this solved for now.
