### ISSUE TITLE
Retry middleware logic for network errors

### ISSUE THREAD

**Issue by wisko** [tulios/mappersmith#98]
In the Retry middleware, the default function `validateRetry` catches all requests that returns a 500 response from the server.
It would be nice to also retry the request if some client error occurs (one of `ECONNRESET`, `ENOTFOUND`, `ESOCKETTIMEDOUT`, `ETIMEDOUT`, `ECONNREFUSED`, `EHOSTUNREACH`, `EPIPE`, `EAI_AGAIN`), when there was no response from the server.
At the moment, the response object from such an error is a status `400`, `Network error`. If the error code could be attached to the response object somehow, it would be easier to add the logic needed to modify the `validateRetry` option. Also, it might be worth considering adding these to the default retry function.

**Comment by tulios** [comment]
Take a look at `response#error`, fixed in version `2.22.0`
